# Generated by Django 5.1.6 on 2025-06-01 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppant_id', models.CharField(max_length=20)),
                ('time_started', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AttentionTestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20, unique=True)),
                ('fake_path', models.CharField(blank=True, max_length=255, null=True)),
                ('real_path', models.CharField(blank=True, max_length=255, null=True)),
                ('times_seen', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['image_id'], name='surveyapp_a_image_i_658a40_idx')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20, unique=True)),
                ('fake_path', models.CharField(blank=True, max_length=255, null=True)),
                ('real_path', models.CharField(blank=True, max_length=255, null=True)),
                ('times_seen', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['image_id'], name='surveyapp_i_image_i_981c37_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdviceStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(max_length=20)),
                ('time_at_submission', models.CharField(max_length=40)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='AdviceEndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(max_length=20)),
                ('time_at_submission', models.CharField(max_length=40)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at_submission', models.DateTimeField()),
                ('time_start', models.CharField(max_length=20)),
                ('response_id', models.CharField(max_length=20)),
                ('image_id', models.CharField(max_length=255)),
                ('choice', models.CharField(max_length=10)),
                ('confidence', models.IntegerField()),
                ('heatmapFill', models.JSONField(default=list)),
                ('assigned_label', models.IntegerField()),
                ('gt', models.IntegerField()),
                ('inconsistency_color', models.IntegerField(default=0)),
                ('inconsistency_boundary', models.IntegerField(default=0)),
                ('inconsistency_landmark', models.IntegerField(default=0)),
                ('inconsistency_texture', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=5)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
    ]
