# Generated by Django 3.2.25 on 2025-01-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppant_id', models.CharField(max_length=20)),
                ('prolificID', models.CharField(max_length=30)),
                ('time_started', models.CharField(max_length=40)),
                ('list_one', models.CharField(choices=[('three', 'three'), ('four', 'four')], default='three', max_length=8)),
                ('list_two', models.CharField(choices=[('three', 'three'), ('four', 'four')], default='three', max_length=8)),
                ('category', models.CharField(choices=[('A', 'no assistance'), ('B', 'just familiar'), ('C', 'intro help')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at_submission', models.CharField(max_length=40)),
                ('response_id', models.CharField(max_length=20)),
                ('image_id', models.CharField(max_length=20)),
                ('choice', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('reasoning', models.CharField(blank=True, max_length=500)),
                ('heatmapFill', models.CharField(blank=True, max_length=500)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='AdviceStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(max_length=20)),
                ('time_at_submission', models.CharField(max_length=40)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='AdviceEndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(max_length=20)),
                ('time_at_submission', models.CharField(max_length=40)),
                ('ppant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.participant')),
            ],
        ),
    ]
