# Generated by Django 5.1.6 on 2025-03-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
