# Generated by Django 5.1.6 on 2025-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_image_times_seen_alter_image_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
        migrations.AddField(
            model_name='image',
            name='fake_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='real_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_id'], name='surveyapp_i_image_i_981c37_idx'),
        ),
    ]
