# Generated by Django 5.2.3 on 2025-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_squashed_0002_response_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviceendtime',
            name='advice_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='advicestarttime',
            name='advice_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='attentiontestimage',
            name='image_id',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ppant_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='time_start',
            field=models.CharField(max_length=50),
        ),
    ]
