# Generated by Django 5.1.6 on 2025-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_remove_image_filename_image_fake_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='inconsistency_type',
            field=models.CharField(choices=[('color', 'Color'), ('boundary', 'Boundary'), ('texture', 'Texture'), ('geometry', 'Geometry')], default='color', max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
