# Generated by Django 5.1.6 on 2025-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_response_inconsistency_type_response_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='inconsistency_type',
            field=models.CharField(choices=[('color', 'Color'), ('boundary', 'Boundary'), ('texture', 'Texture'), ('geometry', 'Geometry'), ('landmark', 'Landmark')], default='color', max_length=50),
        ),
    ]
