# Generated by Django 5.1.6 on 2025-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_alter_response_inconsistency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='assigned_label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='gt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='inconsistency_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='inconsistency_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='inconsistency_geometry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='inconsistency_landmark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='inconsistency_texture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='time_on_question',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='image_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='response',
            name='inconsistency_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
