# Generated by Django 5.1.6 on 2025-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0006_response_assigned_label_response_gt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='inconsistency_type',
        ),
        migrations.RemoveField(
            model_name='response',
            name='reasoning',
        ),
        migrations.AddField(
            model_name='response',
            name='position',
            field=models.CharField(default='left', max_length=10),
        ),
    ]
